### PR TITLE
Suggestions for v2

### PR DESCRIPTION
**Pull request by oxtoacart**
This implements a couple of suggestions.

1. Simplifies the waiting by having the value returned on the waiting channel
2. WithDefault only returns a default value if no real value was available within the specified timeout. The one use of the old DefaultGetter that you found is in a library that we no longer use (afaik), so I wouldn't worry too much about remaining compatible with that. But I think having a default value when no real one was available seems useful.

### CODE REVIEW

**Comment by hwh33** [comment]
Nice, I like these changes.  Your version of `WithDefault` is much better and I think more in the spirit of what this package offers.

The only thing I'd change is to make `value.Locker` normal field, rather than an embedded one.  As it is, one can do:

```
v := eventual.NewValue()
v.(sync.Locker).Lock()
```

I understand that (a) that's unlikely and (b) we'd just be protecting API users from themselves, but it seems better if that's not possible.  I guess it's along the lines of only exporting types, fields, etc. as necessary.

**Comment by hwh33** [comment]
What do you think about that?

**Comment by hwh33** [comment]
Also, I didn't realize you could append to a nil list.  Cool!

**Comment by oxtoacart** [comment]
> make value.Locker a normal field

Sounds like a good idea. Want to just do that on your branch once merged?

> I didn't realize you could append to a nil slice

Yup, and you can iterate over it too :) Having functions work on nil values as much as possible is kind of a Go idiom, though not always well observed.

**Pull request merged**
